name: build
on:
  push:
      branches:
        - master
          pull_reguest :
        jobs:
          build:
            name: build
            runs-on: ubuntu-20.04
              steps: 
                -name:Checkout
                uses: actions/checkout@v2
                - name:Build image
                run:
                  Docker build -t juice-shop:${{github.sha}} .
